### ISSUE TITLE
NDArrayMathCPU and node.js not OK in 0.3.14

### ISSUE THREAD

**Issue by mikkokam** [tensorflow/tfjs-core#438] opened 2017-12-13 16:58 UTC
When running in node.js
`const math = new NDArrayMathCPU();`
will fail -- seems to be trying to use `document`.

older versions work OK for node.js + NDArrayMathCPU.

```
/Users/mikkokam/Documents/git/kerasapi/node_modules/deeplearn/dist/math/backends/webgl/webgl_util.js:7
    var canvas = document.createElement('canvas');
                 ^
ReferenceError: document is not defined
    at Object.createWebGLRenderingContext (/Users/mikkokam/Documents/git/kerasapi/node_modules/deeplearn/dist/math/backends/webgl/webgl_util.js:7:18)
```

**Comment by Lewuathe** [comment] 2017-12-16 03:27
It will be fixed in next release because I could not reproduce by master HEAD.
If you want to try the latest one, this command may help you.

```
$ cd deeplearnjs
$ ./scripts/build-npm.sh
$ mv deeplearn-XXX.tgz /path/to/you-project
$ cd /path/to/your-project
$ npm install deeplearn-XXX.tgz
```

**Comment by erikwilson** [comment] 2017-12-20 14:06
Thanks for addressing this! I know I have lost a few cycles trying to shim this for previous versions when it cropped up. It looks like some more environment tests using karma were added but I wonder if some CPU tests using mocha might help bridge the gap for node. It seems like the team is mostly focused on browser support but it would be nice if a versioned fix were released as soon as possible for these types of issues.

**Comment by dfoody** [comment] 2018-01-03 16:52
@erikwilson @mikkokam - FYI, I've added better support for node+deeplearn.js to a fork of headless-gl:
https://github.com/PAIR-code/deeplearnjs/issues/49#issuecomment-354893620

**Comment by nsthorat** [comment] 2018-04-04 14:38
We're working on official Node.js bindings to the TF C API: https://github.com/tensorflow/tfjs/issues/36

**Closed by nsthorat** 2018-04-04 14:38 UTC
